flows:
  default:
  - var(foo = bar)
  - echo "foo=%foo%"
  
  - var(foolist = [one, two, three])
  - echo "foolist=%foolist%"
  
  - var(foomap = {one = $foo, two = $foolist})
  - echo "foomap=%foomap%"
