flows:
  master:
    - oneops.transitionUpdate(platform = test, component = test, attributes = { module_version = $version })
    - oneops.environmentCommitAndDeploy(platform = test, deployAllPlatforms = false, cancelActiveDeployment = true )
