envs:
  global:
    variables:
      bar:
        one: 1
        two: 2
        three: [foo, bar]

flows:
  default:
  - foreach(one, two, three):
      echo "%key%=%value%"

  - foreach($bar):
      echo "%key%=%value%"

  - foreach('%{bar.three}'):
      echo "%key%=%value%"