envs:
  global:
    variables:
      z: foo
      env2Name: test_env2
  test_env1:
    variables:
      x: abc
      y: 123
      env3:
        y: 567
  test_env2:
    variables:
      x: xyz
      y: 345
flows:
  master:
  - call: test1(test_env1)

  test1:
  - shell: echo %{x} $x
  - call: nested
  - call: nested($env2Name)
  - call: nested($env3)
  - shell: echo %{z} $z

  nested:
  - shell: echo %{y} $y
    