scm:
  checkoutDir: foo

triggers:
  push:
    skipAuthor: 

flows:
  master:
    parallel:
    - ping 127.0.0.1 -n 20 > nul
    - ping 127.0.0.1 -n 20 > nul
    - ping 127.0.0.1 -n 20 > nul
    - ping 127.0.0.1 -n 20 > nul
    - ping 127.0.0.1 -n 20 > nul
    - ping 127.0.0.1 -n 20 > nul
    - ping 127.0.0.1 -n 20 > nul
    - ping 127.0.0.1 -n 20 > nul
