flows:
  default:
  - codegate()

  something(ui test):
#  - try:
    - echo hello
    - try:
      - fail: foo
      catch:
      - echo catch
      - fail: "${flowErrorMessage} bar"
      finally:
      - echo "1 ${flowErrorMessage}"
#    finally:
#    - echo "2 ${flowErrorMessage}"
