envs:
  global:
    variables:
      oneops.variables:
        foo: bar

flows:
  master:
    - oneops.environmentVariableUpdate(organization = 'ukgrsps', assembly = '${assembly}', environment = '${environment}', platform = '${platform}', component = artifact-app, variables = ${oneops.variables})
