envs:
  global:
    variables:
      bar:
        one: 1
        two: 2
        three: [foo, bar]

flows:
  default:
  - foreach(one, two, three): |
      echo "%key%=%value%"
      ping 127.0.0.1 -n 3 > nul

  - foreach($bar): |
      echo "%key%=%value%"
      ping 127.0.0.1 -n 3 > nul

  - foreach('%{bar.three}'): |
      echo "%key%=%value%"
      ping 127.0.0.1 -n 3 > nul
