flows:
  default:
  - codegate()

  something(ui test):
  - try:
    - echo hello
    - try:
      - exit 1
      catch:
      - echo catch
      - exit 1
      finally:
      - echo "1 ${flowErrorMessage}"
    finally:
    - echo "2 ${flowErrorMessage}"
