triggers:
  push: disabled
flows:
  default:
  - codegate()

  something(ui test):
  - try:
    - call: something2
    catch:
    - echo "catch 2 ${flowErrorMessage}"
    finally:
    - echo "2 ${flowErrorMessage}"

  something2(ui test2):
  - echo hello
  - try:
    - fail: foo
    catch:
    - echo "catch 1 ${flowErrorMessage}"
    - fail: bar
    finally:
    - echo "1 ${flowErrorMessage}"
