tools:
  jdk: 8
flows:
  default:
  - codegate()

  something(ui test):
  - try:
    - echo hello
    - try:
      - exit 1
      finally:
      - echo "1 ${flowError}"
    finally:
    - echo "2 ${flowError}"
