triggers:
  - push: disabled
  - pr: disabled

envs:
  global:
    variables:
      foobar: baz

flows:
  default:
  - exposeVars(provider = maven, vars = {PROP_FOO = /properties/foo})
  - echo "$MAVEN_VERSION $PROP_FOO" 
