triggers:
  - push: disabled
  - pr: disabled

tools:
  nodejs:
    - 7.7.2
  npm:
    - 4.1.2
flows:
   master:
   - echo $NPM_CONFIG_GLOBALCONFIG 
   - cat $NPM_CONFIG_GLOBALCONFIG 
   - npm install npm_validation@1.0.0
   #- npm pack --loglevel verbose
   - npm config get foo
   - npm config get registry
   - npm publish
   pr:
   - call: master