envs:
  global:
    variables:
      list:
      - two
      - three
flows:
  default:
  - call: foo(var = one)
  - call: foo(var = $list)
  - call: foo(var = four)
  - call: foo(var = [five, six])

  foo:
    switch($var):
      case(one): echo 11
      case(two, three): echo 2,3
      case(four): echo 4
      otherwise: echo dunno %var%
