triggers:
  - push: disabled
  - pr: disabled
  - cron:
      spec: 12 20 * * *
      timezone: UTC

envs:
  global:
    variables:
      TEST: woo

docker:
  image: 'java:8-jdk-alpine'

flows:
  master(ui Build test1):
    - echo $TEST $test
  test1(ui Build test2):
    - echo test2 $test
