triggers:
  - push: disabled
  - pr: disabled
  - cron:
      spec: H/6 * * * *
      call: test1
  - cron: H/3 * * * * tz:Europe/Tallinn
  - cron:
      spec: 12 22 * * *
      timezone: Europe/Tallinn

envs:
  global:
    variables:
      TEST: ENC[QAzSAxdLAHozhF/vo+AN6w==]

flows:
  master(ui Build test1, on master):
    - echo $TEST $test
  test1(ui Build test2):
    - echo test2 $test
