flows:
  master:
    - ws_snapshot: snap
    - parallel:
      - call: good
      - call: bad
      - call: good
  good:
    - (on centos, exclusive):
      - ws_restore: snap
      - sleep 10
      
  bad:
    - (on centos, exclusive):
      - ws_restore: snap
      - sleep 9 && exit 1
  pr:
    - echo bla
