triggers:
  push: disabled
  pr: disable

tools:
  nodejs: 6.9.1
#  npm: 3.10.8

flows:
  master:
  - parallel:
    - call foo
    - call foo
    - call foo 
  - |
    #!/bin/bash
    which node
    which npm
    npm prefix -g
    npm install -g --verbose bower
    which bower
  foo:
    (name foo):
    - sleep 2