triggers:
  - push: disabled
  - pr: disabled
  - cron:
      spec: H/6 * * * *
      call: test1
  - cron: H/3 * * * *
  - cron:
      spec: 5 13 * * *
      timezone: America/Los_Angeles

envs:
  global:
    variables:
      TEST: ENC[QAzSAxdLAHozhF/vo+AN6w==]

flows:
  master(ui Build test1, on centos):
    - echo $TEST $test
  test1(ui Build test2):
    - echo test2 $test
