triggers:
  push: disabled
  pr: disable

tools:
  maven: 3.3.9
  ant: 1.9.7

envs:
  global:
    variables:
      oneops.organization: platform
      oneops.assembly: TestSterlingLooper
      oneops.environment: QA

flows:
  master:
  - oneops.componentUpdate( attributes = { component = artifact-app, repositoryName = ukgr-snapshot, Version = 1.0.20 })

