triggers:
  push: disabled
  pr: disable
  cron:
    spec: H/5 * * * *
    call: test1

envs:
  global:
    variables:
      TEST: ENC[QAzSAxdLAHozhF/vo+AN6w==]

flows:
  master(ui Build test1):
    - echo $TEST $test
  test1(ui Build test2):
    - echo test2 $test
