triggers:
  - push: disabled
  - pr: disabled
  - cron:
      spec: 12 20 * * *
      timezone: UTC

tools:
  nodejs: 7.4.0
  npm: latest

envs:
  global:
    variables:
      TEST: woo

flows:
  master(ui Build test1, on centos):
    - echo $TEST $test
    - npm -version
  test1(ui Build test2, on centos):
    - echo test2 $test
