triggers:
  push: disabled
  pr: disable

tools:
  maven: 3.3.9
  ant: 1.9.7

envs:
  f1:
    variables:
      foo: f1
  f2:
    variables:
      foo: f2
  f3:
    variables:
      foo: f3

flows:
  master0:
  - (on centos):
    - |
      env
      ls -la $MAVEN_HOME/bin
      echo MVN IS `which mvn`
      mvn help:effective-settings

  master:
  - call: foo(f1)
  - (name foos):
    - call: foo(f2)
    - (on master):
      - echo foo
      - echo bar
    - call: foo(f3)
  
  foo:
  - savepoint
  - echo $foo
  - sleep 5
