tools:
  maven: 3.3.9
  jdk: 1.8.0_102-b14
envs:
  global:
    variables:
      test: Hello random %{Math.random(10000000, 9999999999)}
flows:
  master:
    - ws_snapshot: main
      excludes: target/**
    - (on centos):
      - ws_restore: main
      - echo ${test}
      - mvn clean package -B
  pr:
    - call: master
