triggers:
  pr: disable

tools:
  maven: 3.3.9
  ant: 1.9.7

flows:
  master0:
  - (on centos):
    - |
      env
      ls -la $MAVEN_HOME/bin
      echo MVN IS `which mvn`
      mvn help:effective-settings

  master:
  - parallel:
    - (on centos):
      - (name task1) sleep 2
      - (name task2) sleep 2
    - (on centos):
      - (name task3) sleep 2
      - (name task4) sleep 2

