tools:
  ant: 1.9.7
  jdk: 1.8.0_102-b14
flows:
  master:
    - parallel:
      - |
        (on centos)
        #!/bin/bash -xe
        java -version
        ant -version
      - |
        (on centos)
        sleep 10
        sleep 10
        sleep 10
        sleep 10
  pr:
    - call: master
