triggers:
  push: disabled
  pr: disable

tools:
  maven: 3.3.9
  ant: 1.9.7

flows:
  master0:
  - (on centos):
    - |
      env
      ls -la $MAVEN_HOME/bin
      echo MVN IS `which mvn`
      mvn help:effective-settings

  master:
  - sleep 2
