flows:
  master:
    - ws_snapshot: snap
    - parallel:
      - call: good1
      - call: bad
      - call: good2
      - call: good3
  good1:
    - (on centos, exclusive):
      - ws_restore: snap
      - (name good1) sleep 12
      
  good2:
    - (on centos, exclusive):
      - ws_restore: snap
      - (name good2) sleep 10
  good3:
    - (on centos, exclusive):
      - ws_restore: snap
      - (name good3) sleep 10
      - (name good3_1) sleep 10
  bad:
    - (on centos, exclusive):
      - ws_restore: snap
      - (name bad1) sleep 9 && exit 1
  pr:
    - echo bla
