language: workflow
node_js: 4.2.1
npm: 2.1.4
tools:
  ant: 1.9.7
  jdk: 1.8.0_77-b03
flows:
  master:
    - parallel:
      - (on master) ping 127.0.0.1 -n 20
      - |
        (on centos)
        #!/bin/bash -xe
        ant -version
    - (on master) echo done
  pr:
    - call: master
