triggers:
  push: disabled
  pr: disable

envs:
  global:
    variables:
      TEST: ENC[QAzSAxdLAHozhF/vo+AN6w==]

flows:
  master:
    (on centos):
    - echo $TEST
  test1(ui Build test1):
    - echo test1
  test2(ui Build test2):
    - echo test2
    