envs:
  global:
    variables:
      cmd: sleep 10
      snap: snap
  good1:
    variables:
      name: good1
  good2:
    variables:
      name: good2
  bad:
    variables:
      name: bad
      cmd: sleep 10 && exit1
flows:
  master:
    - ws_snapshot: "%{snap}"
    - parallel:
      - call: gen(good1)
      - call: gen(bad)
      - call: gen(good2)
      - call: good3
  gen:
    - (on centos, exclusive):
      try:
        - ws_restore(name restore %{name}): "%{snap}"
        - (name %{name}) %{cmd}
      finally:
        (name cleanup %{name}) echo "cleaning it up!" && sleep 5
  good3:
    - (on centos, exclusive):
      - ws_restore(name restore good3): "%{snap}"
      - (name good3) %{cmd}
      - (name good3_1) %{cmd}
  pr:
    - echo bla
