triggers:
  - push: disabled
  - pr: disabled
  - cron:
      spec: H/6 * * * *
      call: test1
  - cron: H/3 * * * * tz:Europe/Tallinn
  - cron:
      spec: 08 20 * * *
      timezone: UTC

envs:
  global:
    variables:
      TEST: ENC[QAzSAxdLAHozhF/vo+AN6w==]

flows:
  master(ui Build test1):
    - echo $TEST $test
  test1(ui Build test2):
    - echo test2 $test
