language: workflow
node_js: 4.2.1
npm: 2.1.4
tools:
  jdk: 8

flows:
  master:
    - parallel:
      - (on master) ping 127.0.0.1 -n 20
      - |
        (on centos)
        #!/bin/bash -xe
        RED=$'\e[0;31m'
        NC=$'\e[0m' # No Color
        for i in {1..20}
        do
          printf "Ansi ${RED}color${NC} test\n"
          sleep 3
        done
    - (on master) echo done
  pr:
    - call: master
