tools:
  maven: 3.3.9
  jdk: 1.8.0_102-b14
flows:
  master:
    - ws_snapshot: main
      excludes: target/**
    - (on centos):
      - ws_restore: main
      - mvn clean package -B
  pr:
    - call: master
