triggers:
  push: disabled
  pr: disable

tools:
  maven: 3.3.9

flows:
  master:
  - (on centos):
    - |
      env
      ls -la $MAVEN_HOME/bin
      echo MVN IS `which mvn`
      mvn help:effective-settings
