triggers:
  push: disabled
  pr: disable

tools:
  nodejs: 6.9.1
#  npm: 3.10.8

flows:
  master:
  - parallel:
    - call: foo
    - call: foo
    - call: foo 
  foo:
    (on centos):
    - which node
